# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amnesiai < Formula
  desc "git your ai setup — backup and restore AI coding assistant configurations"
  homepage "https://amnesiai.pixelabs.net"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v1.0.2/amnesiai_darwin_amd64.tar.gz"
      sha256 "421776589ee781d0032f33c0c7e337e5adb7ae99d786954565f7b97714ca3e2c"

      def install
        bin.install "amnesiai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v1.0.2/amnesiai_darwin_arm64.tar.gz"
      sha256 "e50698da5bfd45a672084469461c4b26aaf55147d36ccc515601056c676ea4ff"

      def install
        bin.install "amnesiai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v1.0.2/amnesiai_linux_amd64.tar.gz"
        sha256 "65ab8304fe9d310b4c75558a82b7bd06eca841b574d9b6c681f0bc8afa7f9349"

        def install
          bin.install "amnesiai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v1.0.2/amnesiai_linux_arm64.tar.gz"
        sha256 "b49e6d63ccddb647738224bf824ff7985ed9807b8774154941b47c68b1b89267"

        def install
          bin.install "amnesiai"
        end
      end
    end
  end

  test do
    system "#{bin}/amnesiai", "version"
  end
end
