# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amensiai < Formula
  desc "git your ai setup — backup and restore AI coding assistant configurations"
  homepage "https://amensiai.pixelabs.net"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/thepixelabs/amensiai/releases/download/v1.0.0/amensiai_darwin_amd64.tar.gz"
      sha256 "23f7aa0965180756b9d85bf79adf267269bd3aa200eb2063eb07ea620f511a5a"
    end
    on_arm do
      url "https://github.com/thepixelabs/amensiai/releases/download/v1.0.0/amensiai_darwin_arm64.tar.gz"
      sha256 "e902d46acfb7073d64cfd3cdd095177b6ebdd7899512cc33b124ac09770f36c5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thepixelabs/amensiai/releases/download/v1.0.0/amensiai_linux_amd64.tar.gz"
      sha256 "b1c2359c305d28275ec8b38a9fd75e8b3e9f4bd8bc4160de8462a43db0592f1f"
    end
    on_arm do
      url "https://github.com/thepixelabs/amensiai/releases/download/v1.0.0/amensiai_linux_arm64.tar.gz"
      sha256 "04002135cc7a7670790874d6fe890583cff716b9da0b08f6371690ab846e096d"
    end
  end

  def install
    bin.install "amensiai"
  end

  test do
    system "#{bin}/amensiai", "version"
  end
end
