# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amnesiai < Formula
  desc "git your ai setup — backup and restore AI coding assistant configurations"
  homepage "https://amnesiai.pixelabs.net"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v0.1.0/amnesiai_darwin_amd64.tar.gz"
      sha256 "9fcc9b01ef02a34e51a1a5df5fb9cdefa1cdc119908252ac16db83f7f9070c0d"

      def install
        bin.install "amnesiai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v0.1.0/amnesiai_darwin_arm64.tar.gz"
      sha256 "f3418ed3386ca292126557a8f9a4603ba5c1395429e36256103cbd4b82188b7c"

      def install
        bin.install "amnesiai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v0.1.0/amnesiai_linux_amd64.tar.gz"
        sha256 "919c0244066824e88bb4bcb8c9cc4eefa9eabd536f77c202ed1fe4589718742f"

        def install
          bin.install "amnesiai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v0.1.0/amnesiai_linux_arm64.tar.gz"
        sha256 "dd6e0ccf0625d55fbbc8d1e2e46334d3eab582a6a3589b6ab7ef08631488408a"

        def install
          bin.install "amnesiai"
        end
      end
    end
  end

  test do
    system "#{bin}/amnesiai", "version"
  end
end
