# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amnesiai < Formula
  desc "git your ai setup — backup and restore AI coding assistant configurations"
  homepage "https://amnesiai.pixelabs.net"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v0.2.0/amnesiai_darwin_amd64.tar.gz"
      sha256 "ef7fca94ca3c05e3d3272c93777ce1b2a061638f976e40b5059652856abf09d5"

      def install
        bin.install "amnesiai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v0.2.0/amnesiai_darwin_arm64.tar.gz"
      sha256 "35bf8fb4027d5dcbc3e4101289c7f4ccc5bc9e54002a00e7a5880df403c5415d"

      def install
        bin.install "amnesiai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v0.2.0/amnesiai_linux_amd64.tar.gz"
        sha256 "b064760ba4ba7b886056d614c390f3695fbff5802d8699c49f4711e3de9eebd0"

        def install
          bin.install "amnesiai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v0.2.0/amnesiai_linux_arm64.tar.gz"
        sha256 "d94ea7cad43dc9756c9c95074d525b9bb597b79360d81e11a74bedb12ac47f9a"

        def install
          bin.install "amnesiai"
        end
      end
    end
  end

  test do
    system "#{bin}/amnesiai", "version"
  end
end
