# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amnesiai < Formula
  desc "git your ai setup — backup and restore AI coding assistant configurations"
  homepage "https://amnesiai.pixelabs.net"
  version "1.3.0"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v1.3.0/amnesiai_darwin_amd64.tar.gz"
      sha256 "c279c628912d220f9bd0b8cad5ad2e7d04e5dfb2f32fed61ed64324593172f21"

      def install
        bin.install "amnesiai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thepixelabs/amnesiai/releases/download/v1.3.0/amnesiai_darwin_arm64.tar.gz"
      sha256 "30d8358ff72c261035efdcda57cd257eb334e62c722ad8b3274153287cc28640"

      def install
        bin.install "amnesiai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v1.3.0/amnesiai_linux_amd64.tar.gz"
        sha256 "f023f98f69494b991a733e5f6a4d07d918d10af39764a4f302e308a375aebd5a"

        def install
          bin.install "amnesiai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thepixelabs/amnesiai/releases/download/v1.3.0/amnesiai_linux_arm64.tar.gz"
        sha256 "36f1cdb22684efbce395f985bc2846692e16c5a84cca74c74273592e561e913e"

        def install
          bin.install "amnesiai"
        end
      end
    end
  end

  test do
    system "#{bin}/amnesiai", "version"
  end
end
