# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vedox < Formula
  desc "Local-first, Git-native documentation operating system for solo developers"
  homepage "https://vedox.dev"
  version "0.1.0-alpha.2"
  license "LicenseRef-PolyForm-Shield-1.0.0"

  on_macos do
    url "https://github.com/thepixelabs/Vedox/releases/download/v0.1.0-alpha.2/vedox-0.1.0-alpha.2-darwin-universal.zip"
    sha256 "9a6fff54789b6c00a9c3a4b48dfb720f281b4cfb28507ba8f8cd3761bac83bb6"

    define_method(:install) do
      bin.install "vedox"
      generate_completions_from_executable(bin/"vedox", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thepixelabs/Vedox/releases/download/v0.1.0-alpha.2/vedox-0.1.0-alpha.2-linux-amd64.tar.gz"
      sha256 "8410b67a0dd468de93b485e72b665073225ab8cfadc0bb64315b4fa5378629e1"
      define_method(:install) do
        bin.install "vedox"
        generate_completions_from_executable(bin/"vedox", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thepixelabs/Vedox/releases/download/v0.1.0-alpha.2/vedox-0.1.0-alpha.2-linux-arm64.tar.gz"
      sha256 "2b5c275d78ac4cf4f7c900f752901504ec31d614ecb07d1da1b0737acac89803"
      define_method(:install) do
        bin.install "vedox"
        generate_completions_from_executable(bin/"vedox", "completion")
      end
    end
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  service do
    run [opt_bin/"vedox", "server"]
    keep_alive true
    log_path var/"log/vedox.log"
    error_log_path var/"log/vedox.error.log"
  end

  test do
    assert_match "vedox", shell_output("#{bin}/vedox --version")
  end
end
